version: '3.9'

services:
  mysql_db:
    image: mysql:9.0.1
    environment:
      MYSQL_DATABASE: ccpav
      MYSQL_USER: ccav
      MYSQL_PASSWORD: cheng00..
      MYSQL_ROOT_PASSWORD: cheng00..
    volumes:
      - /Users/cc/Documents/CC_Self/CCFiles/Mysql/data:/var/lib/mysql
      - /Users/cc/Documents/CC_Self/CCFiles/Mysql/conf:/etc/mysql/conf.d
      - /Users/cc/Documents/CC_Self/CCFiles/Mysql/log:/var/log/mysql
    ports:
      - "3306:3306"
    networks:
      - ccnet

  ccav:
    image: ccav:V3
    command: >
      bash -c "while ! nc -z mysql_db 3306; do sleep 5; done;
      python manage.py collectstatic --noinput;
      python manage.py migrate;
      python manage.py runserver 0.0.0.0:8000"  # 启动 Django 服务
    volumes:
      - /Users/cc/Documents/CC_Self/CCFiles/Files:/app/media
      - /Users/cc/Documents/CC_Self/CCFiles/Staticfiles:/app/staticfiles
      - /Users/cc/Documents/CC_Self/CCFiles/logs:/app/logs
    environment:
      - DB_NAME=ccpav
      - DB_USER=root
      - DB_PASSWORD=cheng00..
      - DB_HOST=mysql_db
      - DB_PORT=3306
      - REDIS_URL=redis:6379  # Celery 和 WebSocket 使用 Redis
    ports:
      - "8000:8000"  # Django 服务端口
      - "8899:8899"  # WebSocket 服务端口
    depends_on:
      - mysql_db
      - redis
    networks:
      - ccnet

  nginx:
    image: nginx:stable-perl
    volumes:
      - /Users/cc/Documents/CC_Self/CCFiles/Nginx/conf.d:/etc/nginx/conf.d
      - /Users/cc/Documents/CC_Self/CCFiles/Files:/usr/share/nginx/html
      - /Users/cc/Documents/CC_Self/CCFiles/Staticfiles:/usr/share/staticfiles
      - /Users/cc/Documents/CC_Self/CCFiles/Nginx/logs:/var/log/nginx
    ports:
      - "8888:80"  # Nginx 服务端口
    depends_on:
      - ccav
    networks:
      - ccnet

  redis:
    image: redis:latest
    networks:
      - ccnet

networks:
  ccnet:
    driver: bridge
