# Generated by Django 5.0.7 on 2024-09-19 12:34

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileAppertain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('flag', models.CharField(choices=[('C', 'Catalogue'), ('T', 'Tag')], max_length=1)),
                ('parent', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'file_appertain',
            },
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('md5', models.CharField(max_length=32)),
                ('size', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('type', models.CharField(default='unknown', max_length=16)),
                ('mime', models.CharField(default='unknown', max_length=128)),
                ('level', models.CharField(default='General', max_length=16)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('delete_time', models.DateTimeField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=64, null=True)),
                ('album', models.TextField(blank=True, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('describe', models.TextField(blank=True, null=True)),
                ('hls_addr', models.CharField(blank=True, max_length=128, null=True)),
                ('thumbnail_addr', models.CharField(blank=True, max_length=128, null=True)),
                ('source_addr', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='enable', max_length=16)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'file_info',
            },
        ),
        migrations.CreateModel(
            name='FileRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_appertain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='f_proc.fileappertain')),
                ('file_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='f_proc.fileinfo')),
            ],
            options={
                'db_table': 'file_relationship',
            },
        ),
    ]
